name: Build ontology assets

on:
  workflow_call:
    inputs:
      is_release:
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/python/requirements.txt

      - name: Build combined ontology and schemas
        run: |
          bash ./tools/bash/build/create-combined-turtle.sh src/imaging-ontology/
          python ./tools/python/build/create-schemas.py --input build/ontology_combined.ttl --output build/locales/en/schema.json

      - name: Commit and push built files back to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add build/

          if ! git diff --cached --quiet; then
            git commit -m "Update generated build files"

            # Fetch latest main and rebase
            git fetch origin main
            git rebase origin/main

            git push origin main
          else
            echo "No changes in build folder, nothing to commit."
          fi
