name: Generate respecter HTML

on:
  # workflow_run:
  #   workflows: ["Build ontology assets"]
  #   types:
  #     - completed
  push:
    branches:
      - respecter-ci
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ontology repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install respecter
        run: |
          pip install git+https://github.com/sdsc-ordes/respecter

      - name: Generate ReSpec HTML
        run: |
          respecter ./build/ontology_combined.ttl \
            --config ./tools/respecter/config.yaml \
            --output ./docs/index.html

      - name: Upload generated HTML
        uses: actions/upload-artifact@v4
        with:
          name: respec-html
          path: ./docs/index.html
