name: Run createSchemas.py on push to /schemas

on:
  push:
    paths:
      - 'schemas/**'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-create-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run createSchemas.py
        run: python src/createSchemas.py
      
      - name: Commit changes to current repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add locales/en/schema.json
          git commit -m "Update schema.json [from GitHub Actions]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone second repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sdsc-ordes/imaging-plaza-frontend-public.git
          cd imaging-plaza-frontend-public
          git checkout develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch and commit changes
        run: |
          cd imaging-plaza-frontend-public
          git checkout -b update-schema-${{ github.run_id }}
          cp ../locales/en/schema.json locales/en/
          git add locales/en/schema.json
          git commit -m "Update schema.json [from GitHub Actions]"
          git push origin update-schema-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: sdsc-ordes/imaging-plaza-frontend-public
          base: develop
          head: update-schema-${{ github.run_id }}
          title: "Update schema.json [from GitHub Actions]"
          body: |
            This PR updates the `schema.json` file in the `locales/en` directory.
            Generated by GitHub Actions as part of the workflow.
