name: Main and PR pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  build:
    uses: ./.github/workflows/build.yml
