name: Release workflow

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      is_release: true  # optional, now unused

  checks:
    uses: ./.github/workflows/checks.yml
    needs: build

  make_release:
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v4

      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          name: schema-bundle
          path: build/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
