name: Include ontology assets in the release

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/python/requirements.txt

      - name: Build ontology assets
        run: |
          bash ./tools/bash/build/create-combined-turtle.sh src/imaging-ontology/
          python ./tools/python/build/create-schemas.py --input build/ontology_combined.ttl --output build/locales/en/schema.json

      - name: Upload schema bundle
        uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/tags/v*' }}  # Ensure artifact is uploaded only for tag pushes
        with:
          name: schema-bundle
          path: build/*

  checks:
    uses: ./.github/workflows/checks.yml
    needs: build

  make_release:
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v4

      - name: Get schema assets
        uses: actions/download-artifact@v4.1.8
        with:
          name: schema-bundle
          path: build/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
